---
output: html_document
---

---

# 대학생이 노트북/컴퓨터를 구매할 때 참고 자료

---

#### Team : 정이
#### Date : 21.07.23

---

# CPU
#### 프로그램별 최소 CPU의 벤치마크 점수

```{r echo = FALSE, warning = FALSE, message = FALSE}
install.packages("barplot",repos="http://cran.us.r-project.org")
ex <- read.csv(file='data.csv')
barplot(ex$cpu_score,names.arg=ex$name,col=3:245,main="CPU",
        xlab="Program",ylab="Benchmark",cex.main=1.5,cex.lab=1.2,
        ylim=c(0,20000))
```

---

# GPU
#### 프로그램별 최소 GPU의 벤치마크 점수

```{r echo = FALSE, warning = FALSE, message = FALSE}
install.packages("barplot",repos="http://cran.us.r-project.org")
ex <- read.csv(file='data.csv')
barplot(ex$gpu_score,names.arg=ex$name,col=3:245,main="GPU",
        xlab="Program",ylab="Benchmark",cex.main=1.5,cex.lab=1.2,
        ylim=c(0,10000))
```

---

# Summary
#### 컴퓨터 관련 학과 소속 학생
- 3D 게임 개발을 할 수 있는 Unity, UnrealEngine 등을 사용하기 위해 Benchmark 점수가 최소 18000 정도인 CPU와 10000 정도인 GPU가 장착된 노트북/컴퓨터 추천

#### 영상 편집, 디자인 관련 학과 소속 학생
- Benchmark 점수가 최소 9000 정도인 CPU와 9000 정도인 GPU가 장착된 노트북/컴퓨터 추천

#### 건축 관련 학과 소속 학생
- Benchmark 점수가 최소 10000 정도인 CPU와 8000 정도인 GPU가 장착된 노트북/컴퓨터 추천

---
   
   
   
   
   
   
   
   






